server:
  port: 8001
spring:
  application:
    name: doctor-crud-service
  data:
    mongodb:
      uri: mongodb+srv://mahajanatul525:Sagarpark%2F009@cluster0.lletbme.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: doct
      port: 27017

